name: Build and Sign Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > PROFESSOR/app/PROFESSOR.jks

    - name: Make gradlew executable
      run: chmod +x ./PROFESSOR/gradlew

    - name: Build Release APK
      env:
        KEYSTORE_PASSWORD: "${{ secrets.KEYSTORE_PASSWORD }}"
        KEY_ALIAS: "${{ secrets.KEY_ALIAS }}"
        KEY_PASSWORD: "${{ secrets.KEY_PASSWORD }}"
      run: |
        cd PROFESSOR
        ./gradlew assembleRelease

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: PROFESSOR/app/build/outputs/apk/release/app-release.apk
