name: Generate Keystore

on:
  push:
    branches: [ "main" ]

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
    - name: Generate JKS file
      run: |
        keytool -genkey -v -keystore PROFESSOR.jks -keyalg RSA -keysize 2048 -validity 10000 -alias professor -storepass professor2026 -keypass professor2026 -dname "CN=Professor Gold, OU=App, O=Professor, L=Sanaa, ST=Sanaa, C=YE"

    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: Professor-Keystore
        path: PROFESSOR.jks
